/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        primary: '#00685f',
        'primary-container': '#008378',
        'on-primary': '#ffffff',
        'on-primary-container': '#f4fffc',
        'inverse-primary': '#6bd8cb',
        secondary: '#5c5f61',
        'secondary-container': '#e0e3e5',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#626567',
        tertiary: '#924628',
        'tertiary-container': '#b05e3d',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#fffbff',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3d4947',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#6d7a77',
        'outline-variant': '#bcc9c6',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['Inter', 'monospace'],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        'gutter': '24px',
      },
      borderRadius: {
        'sm': '4px',
        DEFAULT: '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
