import json
import os
from typing import Any, Dict

from dotenv import load_dotenv
from groq import Groq
load_dotenv()

SYSTEM_PROMPT = """
You are the GeneGuard-AI explanation layer.

You receive a structured result generated by a deterministic
whole-exome sequencing analysis pipeline.

Your job is to explain the supplied result clearly for a user.

STRICT RULES:

1. Use ONLY information contained in the supplied JSON.
2. Never invent evidence, clinical history, diagnoses, papers,
   variants, database records, or ACMG criteria.
3. Never change the classification supplied by the pipeline.
4. Never upgrade or downgrade a variant.
5. A criterion with status "candidate" must remain a candidate.
6. Never convert database "not_found" into definitive biological absence.
7. Explain technical terminology in understandable language.
8. Clearly distinguish automated evidence from clinical interpretation.
9. Do not give treatment or medical-management recommendations.
10. State important limitations.
11. Do not claim the result replaces review by a qualified clinician.
12. Do not interpret a numerical score unless the supplied JSON
    explicitly provides the interpretation or threshold.

13. Do not describe a database "not_found" result as proof of
    biological absence.

14. Do not state that there is "no published information" unless
    the supplied JSON explicitly establishes that.

15. Preserve the exact status of every ACMG candidate.

16. Do not introduce outside medical knowledge or thresholds.

Return ONLY valid JSON using exactly these fields:

{
"status": "success",
  "summary": "...",
  "what_was_found": "...",
  "evidence_explanation": "...",
  "classification_explanation": "...",
  "limitations": ["...", "..."],
  "patient_friendly_explanation": "..."
}
"""


def _get_client() -> Groq:
    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY is not configured."
        )

    return Groq(api_key=api_key)


def generate_variant_explanation(
    variant_result: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Generate a human-readable explanation from one
    deterministic WES pipeline result.

    The LLM explains the supplied result.
    It does not perform variant classification.
    """

    client = _get_client()

    user_prompt = (
        "Generate a user-friendly explanation for this "
        "GeneGuard-AI analysis result.\n\n"
        + json.dumps(
            variant_result,
            indent=2,
            default=str
        )
    )

    try:
        response = client.chat.completions.create(
            model=os.getenv(
                "GROQ_EXPLANATION_MODEL",
                "openai/gpt-oss-120b"
            ),
            temperature=0,
            response_format={
                "type": "json_object"
            },
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT
                },
                {
                    "role": "user",
                    "content": user_prompt
                }
            ]
        )

    except Exception as exc:
        raise RuntimeError(
            f"Groq explanation request failed: {exc}"
        ) from exc

    content = response.choices[0].message.content

    if not content:
        raise RuntimeError(
            "Groq returned an empty explanation."
        )

    try:
        explanation = json.loads(content)

    except json.JSONDecodeError as exc:
        raise RuntimeError(
            "Groq returned invalid JSON."
        ) from exc

    required_fields = [
        "status",
        "summary",
        "what_was_found",
        "evidence_explanation",
        "classification_explanation",
        "limitations",
        "patient_friendly_explanation",
    ]

    for field in required_fields:
        if field not in explanation:
            raise RuntimeError(
                f"Groq response is missing field: {field}"
            )

    return explanation