"""remove WES file path

Revision ID: 6512906493ab
Revises: 40c7b21bafdd
Create Date: 2026-09-02 18:16:59.770338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6512906493ab'
down_revision: Union[str, Sequence[str], None] = '40c7b21bafdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wes_reports', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wes_reports', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
