"""family_history_restructure_and_medication_domain

Revision ID: eee1e0e39a52
Revises: 9e04d60c5e52
Create Date: 2026-07-27 05:30:29.825706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eee1e0e39a52'
down_revision: Union[str, Sequence[str], None] = '9e04d60c5e52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=200), nullable=False),
    sa.Column('gene', sa.String(length=50), nullable=False),
    sa.Column('genotype', sa.String(length=100), nullable=True),
    sa.Column('metabolizer_status', sa.String(length=50), nullable=True),
    sa.Column('cpic_recommendation', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_id'), 'medications', ['id'], unique=False)
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.add_column('family_histories', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('family_histories', sa.Column('relationship_label', sa.String(length=100), nullable=True))
    op.add_column('family_histories', sa.Column('sex', sa.String(length=20), nullable=True))
    op.add_column('family_histories', sa.Column('health_status', sa.String(length=50), nullable=True))
    op.add_column('family_histories', sa.Column('diagnosed_conditions', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('family_histories', sa.Column('carrier_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('family_histories', sa.Column('age', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_family_histories_id'), 'family_histories', ['id'], unique=False)
    op.create_index(op.f('ix_family_histories_patient_id'), 'family_histories', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'family_histories', 'family_histories', ['parent_id'], ['id'])
    op.drop_column('family_histories', 'history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_histories', sa.Column('history', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'family_histories', type_='foreignkey')
    op.drop_index(op.f('ix_family_histories_patient_id'), table_name='family_histories')
    op.drop_index(op.f('ix_family_histories_id'), table_name='family_histories')
    op.drop_column('family_histories', 'age')
    op.drop_column('family_histories', 'carrier_status')
    op.drop_column('family_histories', 'diagnosed_conditions')
    op.drop_column('family_histories', 'health_status')
    op.drop_column('family_histories', 'sex')
    op.drop_column('family_histories', 'relationship_label')
    op.drop_column('family_histories', 'parent_id')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_id'), table_name='medications')
    op.drop_table('medications')
    # ### end Alembic commands ###
